export const testData = [
	{
		id: 1,
		address_cate1: "test si",
		address_cate2: "test gu",
		address_cate3: "test dong",

		tumbnail: ["picture.image_url"],
		name: "송수민2",
		gender: "male",
		age: 30,
		company: "한화시스템",
		job: "개발자",
		university: "TestUniversity",
		mbti: "ENTJ",
		smoking_yn: "N",
		kakao_id: "test1234",
		religion: "None",
		charming_point: ["good", "at", "all"],
		filtering_condition: ["No Smoking", "No alchole"],
		deposit_date: new Date(),
		note: "nothing",
		profile_card: "picture.image_url",

		pass_count: 0,
		chance: 2,

		approval_sts: "C",
		matching_sts: "C",

		sts: "C",
		create_dt: new Date(),
		mod_dt: new Date(),
	},
	{
		id: 1,
		address_cate1: "test si",
		address_cate2: "test gu",
		address_cate3: "test dong",
		tumbnail: ["picture.image_url"],
		name: "송수민1",
		gender: "male",
		age: 40,
		company: "한화시스템",
		job: "개발자",
		university: "TestUniversity",
		mbti: "ENTJ",
		smoking_yn: "N",
		kakao_id: "test1234",
		religion: "None",
		charming_point: ["good", "at", "all"],
		filtering_condition: ["No Smoking", "No alchole"],
		deposit_date: new Date(),
		note: "nothing",
		profile_card: "picture.image_url",

		pass_count: 0,
		chance: 2,

		approval_sts: "C",
		matching_sts: "C",

		sts: "C",
		create_dt: new Date(),
		mod_dt: new Date(),
	},
	{
		id: 1,
		address_cate1: "test si",
		address_cate2: "test gu",
		address_cate3: "test dong",
		tumbnail: ["picture.image_url"],
		name: "송수민1",
		gender: "male",
		age: 40,
		company: "한화시스템",
		job: "개발자",
		university: "TestUniversity",
		mbti: "ENTJ",
		smoking_yn: "N",
		kakao_id: "test1234",
		religion: "None",
		charming_point: ["good", "at", "all"],
		filtering_condition: ["No Smoking", "No alchole"],
		deposit_date: new Date(),
		note: "nothing",
		profile_card: "picture.image_url",

		pass_count: 0,
		chance: 2,

		approval_sts: "C",
		matching_sts: "C",

		sts: "C",
		create_dt: new Date(),
		mod_dt: new Date(),
	},
	{
		id: 1,
		address_cate1: "test si",
		address_cate2: "test gu",
		address_cate3: "test dong",
		tumbnail: ["picture.image_url"],
		name: "송수민1",
		gender: "male",
		age: 40,
		company: "한화시스템",
		job: "개발자",
		university: "TestUniversity",
		mbti: "ENTJ",
		smoking_yn: "N",
		kakao_id: "test1234",
		religion: "None",
		charming_point: ["good", "at", "all"],
		filtering_condition: ["No Smoking", "No alchole"],
		deposit_date: new Date(),
		note: "nothing",
		profile_card: "picture.image_url",

		pass_count: 0,
		chance: 2,

		approval_sts: "C",
		matching_sts: "C",

		sts: "C",
		create_dt: new Date(),
		mod_dt: new Date(),
	},
	{
		id: 1,
		address_cate1: "test si",
		address_cate2: "test gu",
		address_cate3: "test dong",
		tumbnail: ["picture.image_url"],
		name: "송수민1",
		gender: "male",
		age: 40,
		company: "한화시스템",
		job: "개발자",
		university: "TestUniversity",
		mbti: "ENTJ",
		smoking_yn: "N",
		kakao_id: "test1234",
		religion: "None",
		charming_point: ["good", "at", "all"],
		filtering_condition: ["No Smoking", "No alchole"],
		deposit_date: new Date(),
		note: "nothing",
		profile_card: "picture.image_url",

		pass_count: 0,
		chance: 2,

		approval_sts: "C",
		matching_sts: "C",

		sts: "C",
		create_dt: new Date(),
		mod_dt: new Date(),
	},
	{
		id: 1,
		address_cate1: "test si",
		address_cate2: "test gu",
		address_cate3: "test dong",
		tumbnail: ["picture.image_url"],
		name: "송수민1",
		gender: "male",
		age: 40,
		company: "한화시스템",
		job: "개발자",
		university: "TestUniversity",
		mbti: "ENTJ",
		smoking_yn: "N",
		kakao_id: "test1234",
		religion: "None",
		charming_point: ["good", "at", "all"],
		filtering_condition: ["No Smoking", "No alchole"],
		deposit_date: new Date(),
		note: "nothing",
		profile_card: "picture.image_url",

		pass_count: 0,
		chance: 2,

		approval_sts: "C",
		matching_sts: "C",

		sts: "C",
		create_dt: new Date(),
		mod_dt: new Date(),
	},
];
