# 워크 플로우 이름
name: Vite React CI

# 워크 플로우가 언제 실행 될지를 정한다.
on:
    push:
        branches:
            - "github-action"

# 동시에 하나의 배포만 허용하도록 구성
concurrency:
    group: "pages"
    cancel-in-progress: true

# 워크플로우에서 할 작업 정의한다.
jobs:
    # 빌드
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  # dist 디렉터리 업로드
                  name: frontend
                  path: "./dist"
    # 테스트
    deploy-dev:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/github-action'

        # 빌드한 artifact 다운로드
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: frontend
                  path: ./dist

            # 개발 서버에 배포
            - name: Deploy to dev server
              uses: appleboy/scp-action@master
              with:
                  host: ${{secrets.DEV_HOST}}
                  username: ${{secrets.DEV_USERNAME}}
                  key: ${{secrets.SSH_KEY2}}
                  source: "./dist"
                  target: "/home/${{secrets.DEV_USERNAME}}/fofo/fofo-webserver/dist"
                  strip_components: 2
